server.port: ${PORT:8080}
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/polymarket
    username: dev
    password: dev
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
polymarket:
  market:
    url: "https://polymarket.com/market/"
    service:
      mock:
        enabled: false
server:
  servlet:
    context-path: /polymarket
