server.port: ${PORT:8080}
spring:
  datasource:
    url: ${POSTGRES_CONNECTION_STRING}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
polymarket:
  market:
    url: "https://polymarket.com/market/"
    service:
      mock:
        enabled: false
